//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.aprendaefaca.cursos.adaptadores;

import android.content.Context;

public final class AdaptadorOpcao_
    extends AdaptadorOpcao
{

    private Context context_;

    private AdaptadorOpcao_(Context context) {
        context_ = context;
        init_();
    }

    public static AdaptadorOpcao_ getInstance_(Context context) {
        return new AdaptadorOpcao_(context);
    }

    private void init_() {
        contexto = context_;
        inicializarAdaptador();
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
