//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.aprendaefaca.cursos.controladores.activities;

import android.content.Context;
import android.os.Bundle;
import android.support.v4.widget.DrawerLayout;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ListView;
import com.aprendaefaca.cursos.R.layout;
import com.aprendaefaca.cursos.adaptadores.AdaptadorOpcao_;
import com.aprendaefaca.cursos.utilitarios.Sessao_;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ControladorTelaActivityPrincipal_
    extends ControladorTelaActivityPrincipal
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_tela_principal);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        baAdaptadorOpcao = AdaptadorOpcao_.getInstance_(this);
        sessao = Sessao_.getInstance_(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ControladorTelaActivityPrincipal_.IntentBuilder_ intent(Context context) {
        return new ControladorTelaActivityPrincipal_.IntentBuilder_(context);
    }

    public static ControladorTelaActivityPrincipal_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new ControladorTelaActivityPrincipal_.IntentBuilder_(fragment);
    }

    public static ControladorTelaActivityPrincipal_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new ControladorTelaActivityPrincipal_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        lvOpcoes = ((ListView) hasViews.findViewById(com.aprendaefaca.cursos.R.id.menu_lateral));
        dlPrincipal = ((DrawerLayout) hasViews.findViewById(com.aprendaefaca.cursos.R.id.drawer_layout));
        if (lvOpcoes!= null) {
            lvOpcoes.setOnItemClickListener(new OnItemClickListener() {


                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                    ControladorTelaActivityPrincipal_.this.clicar(position);
                }

            }
            );
        }
        inicializar();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<ControladorTelaActivityPrincipal_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, ControladorTelaActivityPrincipal_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), ControladorTelaActivityPrincipal_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), ControladorTelaActivityPrincipal_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
