/*--CREATE DATABASE DBLIVRARIA2SEM2019;*/
CREATE DATABASE  teste;

/*--USE DBLIVRARIA2SEM2019;*/
USE teste;

CREATE TABLE AUTOR (
CODIGO_ID_AUT INTEGER AUTO_INCREMENT,
NOME_AUT VARCHAR(60),
PRIMARY KEY (CODIGO_ID_AUT));

CREATE TABLE PAGAMENTO(
CODIGO_ID_PAG INTEGER AUTO_INCREMENT,
DESCRICAO_PAG VARCHAR(30),
PRIMARY KEY (CODIGO_ID_PAG));

CREATE TABLE EDITORA (
CODIGO_ID_ED INTEGER AUTO_INCREMENT,
NOME_ED VARCHAR (60),
PRIMARY KEY (CODIGO_ID_ED));

CREATE TABLE ESTADO (
UF_ID_EST CHAR(2),
DESCRICAO_UF VARCHAR(20),
PRIMARY KEY (UF_ID_EST));

CREATE TABLE CATEGORIA (
CODIGO_ID_CAT INTEGER AUTO_INCREMENT,
DESCRICAO_CAT VARCHAR(30),
PRIMARY KEY (CODIGO_ID_CAT));

CREATE TABLE FORMATO_LIVRO(
CODIGO_ID_FOR INTEGER AUTO_INCREMENT,
DESCRICAO_FOR VARCHAR (20),
PRIMARY KEY (CODIGO_ID_FOR));


CREATE TABLE LIVRO (
ISBN_ID_LIV CHAR(15),
TITULO_LIV VARCHAR(100),
CODIGO_ID_FOR INTEGER,
CODIGO_ID_ED INTEGER,
DTPUBLICACAO_LIV DATE,
VLCUSTO_LIV NUMERIC (10,2),
VLVENDA_LIV NUMERIC (10,2),
PRIMARY KEY (ISBN_ID_LIV),
FOREIGN KEY (CODIGO_ID_FOR) REFERENCES FORMATO_LIVRO(CODIGO_ID_FOR),
FOREIGN KEY (CODIGO_ID_ED) REFERENCES EDITORA (CODIGO_ID_ED));

CREATE TABLE LIVRO_AUTOR(
ISBN_ID_LIV  CHAR(15),
CODIGO_ID_AUT INTEGER,
PRIMARY KEY (ISBN_ID_LIV, CODIGO_ID_AUT),
FOREIGN KEY (ISBN_ID_LIV) REFERENCES LIVRO (ISBN_ID_LIV),
FOREIGN KEY (CODIGO_ID_AUT) REFERENCES AUTOR (CODIGO_ID_AUT));


CREATE TABLE LIVRO_CATEGORIA(
ISBN_ID_LIV CHAR (15),
CODIGO_ID_CAT INTEGER,
PRIMARY KEY (ISBN_ID_LIV, CODIGO_ID_CAT),
FOREIGN KEY (ISBN_ID_LIV) REFERENCES LIVRO (ISBN_ID_LIV),
FOREIGN KEY (CODIGO_ID_CAT) REFERENCES CATEGORIA(CODIGO_ID_CAT));

CREATE TABLE CLIENTE (
LOGIN_ID_CLI VARCHAR(10),
SENHA_CLI VARCHAR(8),
NOME_CLI VARCHAR (50),
CPF_CLI VARCHAR(11),
TELEFONE_CLI VARCHAR(15),
EMAIL_CLI VARCHAR(100),
ENDERECO_CLI VARCHAR(100),
BAIRRO_CLI VARCHAR(20),
CIDADE_CLI VARCHAR(30),
UF_ID_EST CHAR(2),
CEP_CLI VARCHAR (8),
PRIMARY KEY (LOGIN_ID_CLI),
FOREIGN KEY (UF_ID_EST) REFERENCES ESTADO(UF_ID_EST));

CREATE TABLE CARRINHO (
NUMERO_ID_CAR INTEGER AUTO_INCREMENT,
LOGIN_ID_CLI VARCHAR(10),
DATA_PEDID_CAR DATETIME,
DATA_ENTREGA_CAR DATETIME,
CODIGO_ID_PAG INTEGER,
PRIMARY KEY (NUMERO_ID_CAR),
FOREIGN KEY (LOGIN_ID_CLI) REFERENCES CLIENTE (LOGIN_ID_CLI),
FOREIGN KEY (CODIGO_ID_PAG) REFERENCES PAGAMENTO (CODIGO_ID_PAG));

CREATE TABLE ITEM_CARRINHO(
ISBN_ID_LIV CHAR(15),
NUMERO_ID_CAR INTEGER,
QTDADE_ITEM INTEGER,
VLTOTAL_ITEM NUMERIC(10,2),
SITUACAO_ITEM CHAR(1),
PRIMARY KEY (ISBN_ID_LIV, NUMERO_ID_CAR),
FOREIGN KEY (ISBN_ID_LIV) REFERENCES LIVRO (ISBN_ID_LIV),
FOREIGN KEY (NUMERO_ID_CAR)REFERENCES CARRINHO (NUMERO_ID_CAR));
