/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.aprendaefaca.cursos;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int azul=0x7f040004;
        public static final int branco=0x7f040006;
        public static final int laranja=0x7f040000;
        public static final int verde_md=0x7f040001;
        public static final int verde_splash=0x7f040002;
        public static final int verde_telas_fundo=0x7f040003;
        public static final int vermelho=0x7f040005;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively).
    
         */
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
        public static final int navigation_drawer_width=0x7f050002;
    }
    public static final class drawable {
        public static final int android=0x7f020000;
        public static final int c_sharp=0x7f020001;
        public static final int discipline=0x7f020002;
        public static final int drawer_shadow=0x7f020003;
        public static final int exame=0x7f020004;
        public static final int happy=0x7f020005;
        public static final int ic_action_about=0x7f020006;
        public static final int ic_action_camera=0x7f020007;
        public static final int ic_action_cloud=0x7f020008;
        public static final int ic_action_email=0x7f020009;
        public static final int ic_action_gamepad=0x7f02000a;
        public static final int ic_action_good=0x7f02000b;
        public static final int ic_action_group=0x7f02000c;
        public static final int ic_action_help=0x7f02000d;
        public static final int ic_action_import_export=0x7f02000e;
        public static final int ic_action_labels=0x7f02000f;
        public static final int ic_action_search=0x7f020010;
        public static final int ic_action_settings=0x7f020011;
        public static final int ic_action_video=0x7f020012;
        public static final int ic_configuracoes=0x7f020013;
        public static final int ic_drawer=0x7f020014;
        public static final int ic_launcher=0x7f020015;
        public static final int ic_opcoes=0x7f020016;
        public static final int ic_sair=0x7f020017;
        public static final int ic_sobre=0x7f020018;
        public static final int java=0x7f020019;
        public static final int m1=0x7f02001a;
        public static final int media=0x7f02001b;
        public static final int nd=0x7f02001c;
        public static final int ni=0x7f02001d;
        public static final int sad=0x7f02001e;
        public static final int sobre=0x7f02001f;
        public static final int teacher=0x7f020020;
        public static final int user1=0x7f020021;
        public static final int user2=0x7f020022;
        public static final int vb=0x7f020023;
    }
    public static final class id {
        public static final int action_configuracoes=0x7f090014;
        public static final int action_sair=0x7f090016;
        public static final int action_settings=0x7f090013;
        public static final int action_sobre=0x7f090015;
        public static final int btEnviar=0x7f09000b;
        public static final int conteudo_principal=0x7f090005;
        public static final int drawer_layout=0x7f090004;
        public static final int edGostou=0x7f090008;
        public static final int edIndicacao=0x7f090009;
        public static final int edSugestao=0x7f09000a;
        public static final int imageView1=0x7f090011;
        public static final int ivIcone=0x7f090002;
        public static final int laOpcoes=0x7f090001;
        public static final int laPrincipal=0x7f090000;
        public static final int menu_lateral=0x7f090006;
        public static final int rlPrincipal=0x7f090007;
        public static final int tvCursoAndroid=0x7f09000f;
        public static final int tvCursoCSharp=0x7f09000e;
        public static final int tvCursoJava=0x7f09000d;
        public static final int tvCursoVB=0x7f09000c;
        public static final int tvNome=0x7f090003;
        public static final int tvTexto=0x7f090012;
        public static final int tvTexto1=0x7f090010;
    }
    public static final class layout {
        public static final int activity_menu_lateral=0x7f030000;
        public static final int activity_tela_principal=0x7f030001;
        public static final int activity_tela_splash=0x7f030002;
        public static final int fragment_tela_configuracoes=0x7f030003;
        public static final int fragment_tela_cursos=0x7f030004;
        public static final int fragment_tela_sobre=0x7f030005;
    }
    public static final class menu {
        public static final int menu_superior_direito=0x7f080000;
    }
    public static final class string {
        public static final int imagem_aprenda_e_faca_tecnologia=0x7f06000b;
        /**  Tela Splash 
         */
        public static final int imagem_splash_aprenda_e_faca=0x7f060008;
        public static final int texto_actionbar_configuracoes=0x7f060002;
        public static final int texto_actionbar_sair=0x7f060004;
        public static final int texto_actionbar_sobre=0x7f060003;
        /**  Action Bar 
         */
        public static final int texto_actionbar_titulo_opcoes=0x7f060001;
        /**  Tela Sobre 
         */
        public static final int texto_aplicativo_aprenda_e_faca=0x7f060009;
        /**  Tela Configuracoes 
         */
        public static final int texto_botao_enviar=0x7f060007;
        public static final int texto_desenvolvimento_de_software=0x7f06000a;
        public static final int texto_drawer_close=0x7f060006;
        /**  Navigation Drawer 
         */
        public static final int texto_drawer_open=0x7f060005;
        /**  App 
         */
        public static final int texto_nome_do_aplicativo=0x7f060000;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f070000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f070001;
    }
}
