//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.aprendaefaca.cursos.utilitarios;

import android.annotation.TargetApi;
import android.content.Context;
import org.androidannotations.api.view.OnViewChangedNotifier;

@TargetApi(11)
public final class Sessao_
    extends Sessao
{

    private Context context_;
    private static Sessao_ instance_;

    private Sessao_(Context context) {
        context_ = context;
    }

    public static Sessao_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new Sessao_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
    }

}
