//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.aprendaefaca.cursos.controladores.fragments;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.TextView;
import com.aprendaefaca.cursos.R.layout;
import com.aprendaefaca.cursos.utilitarios.Mensagem_;
import com.aprendaefaca.cursos.utilitarios.Sessao_;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ControladorTelaFragmentCursos_
    extends com.aprendaefaca.cursos.controladores.fragments.ControladorTelaFragmentCursos
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_tela_cursos, container, false);
        }
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        sessao = Sessao_.getInstance_(getActivity());
        mensagem = Mensagem_.getInstance_(getActivity());
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ControladorTelaFragmentCursos_.FragmentBuilder_ builder() {
        return new ControladorTelaFragmentCursos_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tvCursoCSharp = ((TextView) hasViews.findViewById(com.aprendaefaca.cursos.R.id.tvCursoCSharp));
        tvCursoVB = ((TextView) hasViews.findViewById(com.aprendaefaca.cursos.R.id.tvCursoVB));
        tvCursoAndroid = ((TextView) hasViews.findViewById(com.aprendaefaca.cursos.R.id.tvCursoAndroid));
        tvCursoJava = ((TextView) hasViews.findViewById(com.aprendaefaca.cursos.R.id.tvCursoJava));
        if (tvCursoVB!= null) {
            tvCursoVB.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ControladorTelaFragmentCursos_.this.redirecionarParaPaginaCursoVb();
                }

            }
            );
        }
        if (tvCursoJava!= null) {
            tvCursoJava.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ControladorTelaFragmentCursos_.this.redirecionarParaPaginaCursoJava();
                }

            }
            );
        }
        if (tvCursoCSharp!= null) {
            tvCursoCSharp.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ControladorTelaFragmentCursos_.this.redirecionarParaPaginaCursoCSharp();
                }

            }
            );
        }
        if (tvCursoAndroid!= null) {
            tvCursoAndroid.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ControladorTelaFragmentCursos_.this.redirecionarParaPaginaCursoAndroid();
                }

            }
            );
        }
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<ControladorTelaFragmentCursos_.FragmentBuilder_, com.aprendaefaca.cursos.controladores.fragments.ControladorTelaFragmentCursos>
    {


        @Override
        public com.aprendaefaca.cursos.controladores.fragments.ControladorTelaFragmentCursos build() {
            ControladorTelaFragmentCursos_ fragment_ = new ControladorTelaFragmentCursos_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
