//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.aprendaefaca.cursos.controladores.fragments;

import android.annotation.TargetApi;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import com.aprendaefaca.cursos.R.layout;
import com.aprendaefaca.cursos.utilitarios.Mensagem_;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

@TargetApi(11)
public final class ControladorTelaFragmentConfiguracao_
    extends com.aprendaefaca.cursos.controladores.fragments.ControladorTelaFragmentConfiguracao
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_tela_configuracoes, container, false);
        }
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        mensagem = Mensagem_.getInstance_(getActivity());
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ControladorTelaFragmentConfiguracao_.FragmentBuilder_ builder() {
        return new ControladorTelaFragmentConfiguracao_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        edSugestao = ((EditText) hasViews.findViewById(com.aprendaefaca.cursos.R.id.edSugestao));
        edIndicacao = ((EditText) hasViews.findViewById(com.aprendaefaca.cursos.R.id.edIndicacao));
        edGostou = ((EditText) hasViews.findViewById(com.aprendaefaca.cursos.R.id.edGostou));
        btEnviar = ((Button) hasViews.findViewById(com.aprendaefaca.cursos.R.id.btEnviar));
        if (btEnviar!= null) {
            btEnviar.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ControladorTelaFragmentConfiguracao_.this.configurar();
                }

            }
            );
        }
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<ControladorTelaFragmentConfiguracao_.FragmentBuilder_, com.aprendaefaca.cursos.controladores.fragments.ControladorTelaFragmentConfiguracao>
    {


        @Override
        public com.aprendaefaca.cursos.controladores.fragments.ControladorTelaFragmentConfiguracao build() {
            ControladorTelaFragmentConfiguracao_ fragment_ = new ControladorTelaFragmentConfiguracao_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
