//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.aprendaefaca.cursos.utilitarios;

import android.content.Context;
import android.os.Handler;
import android.os.Looper;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class Mensagem_
    extends Mensagem
{

    private Context context_;
    private static Mensagem_ instance_;
    private Handler handler_ = new Handler(Looper.getMainLooper());

    private Mensagem_(Context context) {
        context_ = context;
    }

    public static Mensagem_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new Mensagem_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
    }

    @Override
    public void exibirMensagem(final Context contexto, final String mensagem) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                Mensagem_.super.exibirMensagem(contexto, mensagem);
            }

        }
        );
    }

}
